language: ruby
services:
  - redis
rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.0
env:
  matrix:
    - SIDEKIQ_VERSION="~> 2.6.0"
    - SIDEKIQ_VERSION="~> 2.17.0"
    - SIDEKIQ_VERSION="~> 3.0.0"
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - pablo@pablocantero.com
